export interface BlessingItem {
  id: number;
  quote: string;
  text: string;
}

export const DEFAULT_BLESSINGS: BlessingItem[] = [
  { id: 0, quote: "Giờ Cha Chờ", text: "Năm mới, Chúa mời gọi bạn siêng năng chạy đến với Người qua Bí Tích Hòa Giải và Thánh Lễ. Tải ứng dụng Giờ Cha Chờ tra cứu Giờ Lễ & Giờ Xưng Tội tại cửa hàng ứng dụng di động." },
  { id: 1, quote: "Ds 6,24-26", text: "Xin Chúa chúc lành, gìn giữ và ban bình an cho anh/chị trong năm mới." },
  { id: 2, quote: "Tv 23,1", text: "Năm nay, anh/chị đừng lo thiếu thốn, vì Chúa là Đấng chăn dắt đời mình." },
  { id: 3, quote: "Tv 23,3", text: "Xin Chúa bổ sức tâm hồn và dẫn anh/chị đi trên đường ngay lành." },
  { id: 4, quote: "Tv 23,4", text: "Dù năm mới có điều chưa biết trước, anh/chị vẫn không đơn độc vì Chúa ở cùng." },
  { id: 5, quote: "Tv 27,1", text: "Chúa là ánh sáng của đời anh/chị; xin năm mới không còn sợ hãi." },
  { id: 6, quote: "Tv 29,11", text: "Xin Chúa ban sức mạnh và chúc lành bình an cho gia đình anh/chị." },
  { id: 7, quote: "Tv 31,25", text: "Hãy vững lòng, vì Chúa sẽ làm cho trái tim anh/chị mạnh mẽ hơn." },
  { id: 8, quote: "Tv 34,9", text: "Xin cho anh/chị cảm nhận được Chúa tốt lành trong từng ngày của năm mới." },
  { id: 9, quote: "Tv 37,4", text: "Hãy vui trong Chúa, Người sẽ chăm sóc những ước nguyện đẹp trong lòng anh/chị." },
  { id: 10, quote: "Tv 37,5", text: "Hãy phó thác đường đời cho Chúa, Người sẽ âm thầm mở lối cho anh/chị." },
  { id: 11, quote: "Tv 46,2", text: "Khi lòng chao đảo, xin anh/chị nhớ rằng Chúa là nơi nương náu vững vàng." },
  { id: 12, quote: "Tv 55,23", text: "Hãy trao những gánh nặng cũ cho Chúa, để bước vào năm mới nhẹ lòng hơn." },
  { id: 13, quote: "Tv 65,12", text: "Xin Chúa đội triều thiên ân phúc cho năm mới của anh/chị." },
  { id: 14, quote: "Tv 84,12", text: "Chúa chẳng từ chối điều tốt lành cho ai sống chân thành trước mặt Người." },
  { id: 15, quote: "Tv 85,9", text: "Xin bình an của Chúa trở về trong lòng và trong mái nhà anh/chị." },
  { id: 16, quote: "Tv 90,17", text: "Xin Chúa cho công việc tay anh/chị làm trong năm mới được vững bền." },
  { id: 17, quote: "Tv 91,11", text: "Xin Chúa sai thiên thần gìn giữ anh/chị trên mọi nẻo đường năm nay." },
  { id: 18, quote: "Tv 103,2", text: "Năm mới, xin anh/chị đừng quên bao ơn lành Chúa đã âm thầm ban." },
  { id: 19, quote: "Tv 118,24", text: "Đây là ngày Chúa làm ra; xin anh/chị vui lên và bắt đầu lại trong hy vọng." },
  { id: 20, quote: "Tv 121,5", text: "Chúa là Đấng canh giữ đời anh/chị, như bóng mát chở che bên cạnh." },
  { id: 21, quote: "Tv 121,7", text: "Xin Chúa gìn giữ anh/chị khỏi điều dữ và giữ tâm hồn luôn bình an." },
  { id: 22, quote: "Tv 121,8", text: "Xin Chúa gìn giữ anh/chị khi ra đi, lúc trở về, suốt cả năm mới." },
  { id: 23, quote: "Tv 126,5", text: "Ai đã gieo trong nước mắt, sẽ có ngày gặt trong tiếng cười." },
  { id: 24, quote: "Tv 127,1", text: "Xin Chúa xây dựng gia đình và công việc của anh/chị trong năm mới." },
  { id: 25, quote: "Tv 128,1-2", text: "Phúc cho ai kính sợ Chúa; họ sẽ hưởng thành quả do tay mình làm ra." },
  { id: 26, quote: "Tv 145,18", text: "Khi anh/chị thật lòng kêu cầu, Chúa luôn ở gần." },
  { id: 27, quote: "Cn 3,5-6", text: "Hãy tin tưởng Chúa, Người sẽ làm cho đường anh/chị đi được ngay thẳng." },
  { id: 28, quote: "Cn 16,3", text: "Hãy trao việc mình làm cho Chúa, dự định của anh/chị sẽ được Người nâng đỡ." },
  { id: 29, quote: "Gv 3,11", text: "Chúa làm mọi sự tốt đẹp đúng thời điểm của Người." },
  { id: 30, quote: "Is 26,3", text: "Ai cậy trông nơi Chúa sẽ được Người giữ gìn trong bình an." },
  { id: 31, quote: "Is 30,15", text: "Trong thinh lặng và tin tưởng, anh/chị sẽ tìm lại sức mạnh cho năm mới." },
  { id: 32, quote: "Is 35,4", text: "Hãy can đảm lên, đừng sợ; Thiên Chúa đang đến để cứu giúp anh/chị." },
  { id: 33, quote: "Is 40,29", text: "Chúa ban sức mạnh cho người mệt mỏi và nâng đỡ ai kiệt sức." },
  { id: 34, quote: "Is 40,31", text: "Ai trông cậy Chúa sẽ được thêm sức mới để bước tiếp." },
  { id: 35, quote: "Is 41,10", text: "Đừng sợ, vì Chúa ở cùng anh/chị và nâng đỡ anh/chị." },
  { id: 36, quote: "Is 41,13", text: "Chúa nắm lấy tay anh/chị và nói: đừng sợ, có Ta trợ giúp." },
  { id: 37, quote: "Is 43,1", text: "Chúa gọi anh/chị bằng tên; anh/chị thuộc về Người." },
  { id: 38, quote: "Is 43,2", text: "Qua nước sâu hay lửa thử thách, Chúa vẫn ở cùng anh/chị." },
  { id: 39, quote: "Is 43,19", text: "Năm mới, Chúa đang làm một điều mới và mở đường giữa nơi tưởng như bế tắc." },
  { id: 40, quote: "Is 44,3", text: "Xin Chúa đổ phúc lành xuống trên gia đình và con cháu anh/chị." },
  { id: 41, quote: "Is 46,4", text: "Chúa vẫn bồng ẵm, nâng niu và cứu giúp anh/chị qua từng mùa đời." },
  { id: 42, quote: "Is 49,15", text: "Dù ai quên anh/chị, Chúa vẫn không bao giờ quên." },
  { id: 43, quote: "Is 54,10", text: "Núi có dời, đồi có chuyển, tình thương Chúa dành cho anh/chị vẫn không đổi." },
  { id: 44, quote: "Is 58,11", text: "Chúa sẽ luôn dẫn dắt và làm tâm hồn anh/chị như khu vườn được tưới mát." },
  { id: 45, quote: "Is 60,1", text: "Hãy đứng lên và tỏa sáng, vì ánh sáng của Chúa đã đến với anh/chị." },
  { id: 46, quote: "Gr 17,7", text: "Phúc cho người đặt niềm tin nơi Chúa, vì lòng họ có chỗ tựa vững bền." },
  { id: 47, quote: "Gr 17,8", text: "Người cậy trông Chúa như cây bên dòng nước, vẫn xanh tươi trong ngày nắng hạn." },
  { id: 48, quote: "Gr 29,11", text: "Chúa có kế hoạch bình an và tương lai đầy hy vọng cho anh/chị." },
  { id: 49, quote: "Gr 31,3", text: "Chúa yêu anh/chị bằng tình yêu muôn thuở." },
  { id: 50, quote: "Ac 3,22-23", text: "Lòng thương xót Chúa luôn mới mỗi buổi sáng; năm mới cũng là một khởi đầu mới." },
  { id: 51, quote: "Ed 36,26", text: "Xin Chúa ban cho anh/chị một trái tim mới, mềm mại và bình an hơn." },
  { id: 52, quote: "Ge 2,21", text: "Đừng sợ, hãy vui mừng, vì Chúa đang thực hiện những điều lớn lao." },
  { id: 53, quote: "Mk 7,7", text: "Dù có vấp ngã, anh/chị vẫn có thể đứng lên nhờ Chúa là ánh sáng." },
  { id: 54, quote: "Na 1,7", text: "Chúa tốt lành, là thành lũy chở che trong ngày gian khó." },
  { id: 55, quote: "Xp 3,17", text: "Chúa ở giữa anh/chị, vui mừng vì anh/chị và lấy tình thương mà đổi mới." },
  { id: 56, quote: "Mt 5,4", text: "Phúc cho ai sầu khổ, vì họ sẽ được Thiên Chúa ủi an." },
  { id: 57, quote: "Mt 5,5", text: "Phúc cho ai hiền lành, vì Chúa sẽ ban cho họ phần gia nghiệp tốt đẹp." },
  { id: 58, quote: "Mt 5,7", text: "Phúc cho ai biết xót thương, vì họ sẽ được Chúa xót thương." },
  { id: 59, quote: "Mt 5,9", text: "Phúc cho ai xây dựng hòa bình, vì họ được gọi là con Thiên Chúa." },
  { id: 60, quote: "Mt 6,26", text: "Chúa chăm sóc chim trời, huống chi là anh/chị quý giá trước mặt Người." },
  { id: 61, quote: "Mt 6,31-33", text: "Đừng quá lo lắng; hãy tìm Chúa trước, Người sẽ lo liệu điều cần thiết." },
  { id: 62, quote: "Mt 7,7", text: "Hãy xin, hãy tìm, hãy gõ; Chúa sẽ mở cửa cho anh/chị." },
  { id: 63, quote: "Mt 11,28", text: "Hãy đến với Chúa khi mỏi mệt, Người sẽ cho anh/chị được nghỉ ngơi." },
  { id: 64, quote: "Mt 11,29", text: "Hãy học với Chúa sự hiền lành và khiêm nhường, tâm hồn anh/chị sẽ được an nghỉ." },
  { id: 65, quote: "Mt 19,26", text: "Với Thiên Chúa, điều tưởng như không thể vẫn có thể thành hiện thực." },
  { id: 66, quote: "Mt 28,20", text: "Chúa ở cùng anh/chị mọi ngày trong năm mới này." },
  { id: 67, quote: "Mc 5,36", text: "Đừng sợ, chỉ cần tin thôi." },
  { id: 68, quote: "Mc 9,23", text: "Ai tin thì mọi sự đều có thể trong quyền năng Chúa." },
  { id: 69, quote: "Mc 10,27", text: "Điều con người không làm được, Thiên Chúa vẫn làm được." },
  { id: 70, quote: "Lc 1,37", text: "Không có gì là không thể đối với Thiên Chúa." },
  { id: 71, quote: "Lc 1,45", text: "Phúc cho ai tin rằng Chúa sẽ thực hiện lời Người đã hứa." },
  { id: 72, quote: "Lc 2,14", text: "Xin bình an của Chúa ở với anh/chị và gia đình trong năm mới." },
  { id: 73, quote: "Lc 6,36", text: "Xin cho trái tim anh/chị trong năm mới biết nhân từ như Cha trên trời." },
  { id: 74, quote: "Lc 10,20", text: "Hãy vui mừng vì tên anh/chị được ghi trong tình thương của Chúa." },
  { id: 75, quote: "Lc 12,32", text: "Đừng sợ, vì Cha trên trời vui lòng ban điều tốt lành cho anh/chị." },
  { id: 76, quote: "Ga 8,12", text: "Ai theo Chúa sẽ không đi trong tối tăm nhưng có ánh sáng sự sống." },
  { id: 77, quote: "Ga 10,10", text: "Chúa đến để anh/chị được sống và sống dồi dào hơn." },
  { id: 78, quote: "Ga 14,1", text: "Đừng để lòng xao xuyến; hãy tin vào Thiên Chúa." },
  { id: 79, quote: "Ga 14,27", text: "Chúa ban cho anh/chị bình an không giống bình an chóng qua của thế gian." },
  { id: 80, quote: "Ga 15,5", text: "Ở lại trong Chúa, đời anh/chị sẽ sinh nhiều hoa trái tốt lành." },
  { id: 81, quote: "Ga 15,9", text: "Hãy ở lại trong tình yêu của Chúa suốt năm mới này." },
  { id: 82, quote: "Ga 15,11", text: "Xin niềm vui của Chúa ở trong anh/chị và làm cho niềm vui ấy nên trọn vẹn." },
  { id: 83, quote: "Ga 16,33", text: "Hãy can đảm, vì Chúa đã thắng thế gian." },
  { id: 84, quote: "Cv 20,35", text: "Cho đi với tình yêu, anh/chị sẽ nhận lại niềm vui sâu hơn." },
  { id: 85, quote: "Rm 5,5", text: "Niềm hy vọng nơi Chúa không làm anh/chị thất vọng." },
  { id: 86, quote: "Rm 8,28", text: "Chúa làm cho mọi sự sinh ích cho những ai yêu mến Người." },
  { id: 87, quote: "Rm 8,31", text: "Nếu Thiên Chúa bênh đỡ anh/chị, còn gì phải sợ?" },
  { id: 88, quote: "Rm 8,39", text: "Không gì có thể tách anh/chị khỏi tình yêu của Thiên Chúa." },
  { id: 89, quote: "Rm 12,12", text: "Hãy vui mừng trong hy vọng, kiên nhẫn khi gian truân và bền lòng cầu nguyện." },
  { id: 90, quote: "Rm 15,13", text: "Xin Thiên Chúa là nguồn hy vọng đổ đầy niềm vui và bình an trong lòng anh/chị." },
  { id: 91, quote: "1 Cr 2,9", text: "Chúa chuẩn bị cho người yêu mến Người những điều vượt quá điều lòng người tưởng nghĩ." },
  { id: 92, quote: "1 Cr 13,4", text: "Xin tình yêu trong gia đình anh/chị năm mới này thêm nhẫn nại và hiền hậu." },
  { id: 93, quote: "2 Cr 5,17", text: "Trong Đức Kitô, anh/chị được bắt đầu lại như một thụ tạo mới." },
  { id: 94, quote: "2 Cr 9,8", text: "Chúa có thể ban dư đầy ân sủng để anh/chị luôn đủ sức làm điều lành." },
  { id: 95, quote: "2 Cr 12,9", text: "Ơn Chúa đủ cho anh/chị, nhất là trong những lúc yếu lòng." },
  { id: 96, quote: "Gl 5,22", text: "Xin Thánh Thần ban cho anh/chị yêu thương, vui mừng, bình an và hiền hòa." },
  { id: 97, quote: "Gl 6,9", text: "Đừng nản lòng khi làm điều thiện, vì đến mùa, anh/chị sẽ gặt hái." },
  { id: 98, quote: "Ep 3,20", text: "Chúa có thể làm cho anh/chị hơn cả điều anh/chị cầu xin hay nghĩ tới." },
  { id: 99, quote: "Pl 1,6", text: "Chúa đã khởi sự điều tốt lành nơi anh/chị và sẽ hoàn tất điều ấy." },
  { id: 100, quote: "Pl 4,7", text: "Xin bình an của Thiên Chúa gìn giữ lòng trí anh/chị trong năm mới." }
];

export const CHRISTMAS_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Lc 2,14", text: "Vinh danh Thiên Chúa trên trời, bình an dưới thế cho loài người Chúa thương." },
  { id: 2, quote: "Is 9,5", text: "Một trẻ thơ đã sinh ra cho chúng ta, một người con đã được ban tặng cho chúng ta." },
  { id: 3, quote: "Mt 1,23", text: "Này đây, Trinh Nữ sẽ thụ thai và sinh hạ một con trai, người ta sẽ gọi tên con trẻ là Em-ma-nu-en, nghĩa là Thiên-Chúa-ở-cùng-chúng-ta." },
  { id: 4, quote: "Ga 1,14", text: "Ngôi Lời đã trở nên người phàm và cư ngụ giữa chúng ta." },
  { id: 5, quote: "Ga 8,12", text: "Tôi là ánh sáng thế gian. Ai theo tôi, sẽ nhận được ánh sáng đem lại sự sống." },
  { id: 6, quote: "Lc 2,10-11", text: "Anh em đừng sợ, vì này tôi báo cho anh em một tin mừng trọng đại: Hôm nay, một Đấng Cứu Độ đã sinh ra." },
  { id: 7, quote: "Is 7,14", text: "Chính Chúa Thượng sẽ ban cho các ngươi một dấu hiệu: Này đây người thiếu nữ mang thai, sinh hạ con trai." },
  { id: 8, quote: "Lc 1,35", text: "Thần Khí Thánh sẽ ngự xuống trên bà, và quyền năng Đấng Tối Cao sẽ rợp bóng trên bà." },
  { id: 9, quote: "Ga 3,16", text: "Thiên Chúa yêu thế gian đến nỗi đã ban Con Một, để ai tin vào Con của Người thì khỏi phải chết, nhưng được sống muôn đời." },
  { id: 10, quote: "Rm 15,13", text: "Xin Thiên Chúa là nguồn hy vọng, ban cho anh em được đầy tràn niềm vui và bình an." },
  { id: 11, quote: "Pl 4,4", text: "Anh em hãy vui luôn trong niềm vui của Chúa." },
  { id: 12, quote: "1 Ga 4,9", text: "Tình yêu của Thiên Chúa đối với chúng ta được biểu lộ qua việc Người đã sai Con Một đến thế gian." },
  { id: 13, quote: "Tt 3,4", text: "Thiên Chúa, Đấng cứu độ chúng ta, đã biểu lộ lòng nhân hậu và tình thương của Người đối với nhân loại." },
  { id: 14, quote: "Is 9,1", text: "Dân đang đi trong tăm tối đã nhìn thấy một ánh sáng huy hoàng." },
  { id: 15, quote: "Lc 1,78-79", text: "Thiên Chúa ta đầy lòng trắc ẩn, cho Vầng Đông tự chốn cao vời viếng thăm ta." },
  { id: 16, quote: "Ga 1,9", text: "Ngôi Lời là ánh sáng thật, ánh sáng đến thế gian và chiếu soi mọi người." },
  { id: 17, quote: "Gc 1,17", text: "Mọi ơn lành và mọi phúc lộc hoàn hảo đều do từ trên ban xuống, từ Cha các dòng sáng." },
  { id: 18, quote: "Is 11,1", text: "Từ gốc tổ Gie-sê, sẽ đâm ra một nhánh nhỏ, từ cội rễ ấy, sẽ mọc lên một mầm non." },
  { id: 19, quote: "Lc 2,30-31", text: "Chính mắt con được thấy ơn cứu độ Chúa đã dành sẵn cho muôn dân." },
  { id: 20, quote: "Ga 14,27", text: "Thầy để lại bình an cho anh em, Thầy ban bình an của Thầy cho anh em." },
  { id: 21, quote: "Cl 3,15", text: "Ước gì ơn bình an của Đức Kitô làm chủ tâm hồn anh em." },
  { id: 22, quote: "Is 52,7", text: "Đẹp đẽ thay trên núi đồi bước chân người loan báo tin mừng, công bố bình an." },
  { id: 23, quote: "Gr 29,11", text: "Ta biết các kế hoạch Ta định làm cho các ngươi, kế hoạch thịnh vượng chứ không phải tai ương." },
  { id: 24, quote: "Mt 2,10", text: "Khi thấy ngôi sao, các nhà chiêm tinh vui mừng khôn xiết tả." },
  { id: 25, quote: "Is 60,1", text: "Đứng lên, bừng sáng lên, vì ánh sáng của ngươi đã đến, vinh quang của Đức Chúa đã bừng lên trên ngươi." },
  { id: 26, quote: "2 Cr 9,15", text: "Tạ ơn Thiên Chúa vì quà tặng khôn tả của Người." },
  { id: 27, quote: "Lc 1,46-47", text: "Linh hồn tôi ngợi khen Đức Chúa, thần trí tôi hớn hở vui mừng vì Thiên Chúa Đấng cứu độ tôi." },
  { id: 28, quote: "Is 9,6", text: "Người được gọi là Cố Vấn kỳ diệu, Thần Lực dũng mãnh, Người Cha muôn thuở, Thủ Lãnh hòa bình." },
  { id: 29, quote: "Ga 16,33", text: "Thầy nói với anh em những điều ấy, để trong Thầy anh em có bình an." },
  { id: 30, quote: "Lc 2,20", text: "Các mục đồng ra về, vừa đi vừa tôn vinh ca tụng Thiên Chúa vì mọi điều họ đã nghe và thấy." },
  { id: 31, quote: "1 Ga 4,19", text: "Chúng ta hãy yêu thương, vì Thiên Chúa đã yêu thương chúng ta trước." },
  { id: 32, quote: "Ep 2,14", text: "Chính Đức Kitô là bình an của chúng ta, Người đã liên kết đôi bên thành một." },
  { id: 33, quote: "1 Ga 1,5", text: "Thiên Chúa là ánh sáng; nơi Người không có một chút bóng tối nào." },
  { id: 34, quote: "Is 12,3", text: "Các bạn sẽ hân hoan múc nước tận nguồn ơn cứu độ." },
  { id: 35, quote: "Lc 1,30", text: "Thưa bà Maria, xin đừng sợ, vì bà đẹp lòng Thiên Chúa." },
  { id: 36, quote: "Lc 2,40", text: "Hài Nhi ngày càng lớn lên, thêm vững mạnh, đầy khôn ngoan, và hằng được ân nghĩa cùng Thiên Chúa." },
  { id: 37, quote: "Ga 1,4", text: "Ở nơi Người vẫn có sự sống, và sự sống ấy là ánh sáng cho nhân loại." },
  { id: 38, quote: "Is 40,3", text: "Có tiếng hô: Trong sa mạc, hãy dọn đường cho Đức Chúa, giữa đất hoang, hãy vạch một con lộ thẳng băng cho Thiên Chúa chúng ta." },
  { id: 39, quote: "Pl 4,7", text: "Bình an của Thiên Chúa, bình an vượt lên trên mọi hiểu biết, sẽ giữ gìn lòng trí anh em." },
  { id: 40, quote: "1 Pr 1,8", text: "Tuy không thấy Người, anh em vẫn yêu mến, tin vào Người và được chan chứa một niềm vui khôn tả." },
  { id: 41, quote: "1 Ga 3,1", text: "Anh em hãy xem Chúa Cha yêu chúng ta dường nào: Người cho chúng ta được gọi là con Thiên Chúa." },
  { id: 42, quote: "Is 25,9", text: "Đây là Chúa chúng ta thờ kính, hãy reo mừng và hân hoan vì Người ban ơn cứu độ." },
  { id: 43, quote: "2 Cr 8,9", text: "Đức Giêsu Kitô đã tự ý trở nên nghèo khó vì anh em, để anh em được trở nên giàu có nhờ cái nghèo của Người." },
  { id: 44, quote: "1 Ga 5,11", text: "Thiên Chúa đã ban cho chúng ta sự sống đời đời, và sự sống ấy ở trong Con của Người." },
  { id: 45, quote: "Is 61,10", text: "Tôi hớn hở vui mừng trong Đức Chúa, hồn tôi nhảy múa trong Thiên Chúa tôi thờ." }
];

export const EASTER_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Ga 11,25", text: "Chính Thầy là sự sống lại và là sự sống. Ai tin vào Thầy, thì dù đã chết, cũng sẽ được sống." },
  { id: 2, quote: "Rm 6,9", text: "Đức Kitô một khi đã sống lại từ cõi chết, thì không bao giờ chết nữa, cái chết chẳng còn quyền gì đối với Người." },
  { id: 3, quote: "1 Pr 1,3", text: "Chúc tụng Thiên Chúa là Cha Đức Giêsu Kitô! Người đã tái sinh chúng ta vào một niềm hy vọng sống động nhờ Đức Giêsu Kitô đã sống lại từ cõi chết." },
  { id: 4, quote: "Ga 14,19", text: "Vì Thầy sống, nên anh em cũng sẽ được sống." },
  { id: 5, quote: "Rm 8,11", text: "Nếu Thần Khí của Đấng đã làm cho Đức Giêsu sống lại từ cõi chết ngự trong anh em, thì Người cũng sẽ cho thân xác hay chết của anh em được sự sống mới." },
  { id: 6, quote: "Ga 20,29", text: "Phúc cho những ai không thấy mà tin." },
  { id: 7, quote: "Lc 24,5-6", text: "Sao các chị lại tìm Đấng Sống ở giữa kẻ chết? Người không còn ở đây nữa, nhưng đã trỗi dậy rồi." },
  { id: 8, quote: "Ga 10,18", text: "Mạng sống của Ta, không ai lấy đi được, nhưng chính Ta tự ý đặt mạng sống ấy." },
  { id: 9, quote: "Rm 6,4", text: "Chúng ta đã cùng được mai táng với Đức Kitô, để như Người đã sống lại từ cõi chết thế nào, chúng ta cũng được sống một đời sống mới như vậy." },
  { id: 10, quote: "1 Cr 15,20", text: "Đức Kitô đã trỗi dậy từ cõi chết, mở đường cho những ai đã an giấc ngàn thu." },
  { id: 11, quote: "Ga 20,19", text: "Đức Giêsu đến, đứng giữa các ông và nói: Bình an cho anh em!" },
  { id: 12, quote: "Cl 3,1", text: "Anh em đã được trỗi dậy cùng với Đức Kitô, nên hãy tìm kiếm những gì thuộc thượng giới, nơi Đức Kitô đang ngự bên hữu Thiên Chúa." },
  { id: 13, quote: "1 Cr 15,57", text: "Tạ ơn Thiên Chúa, Đấng ban cho chúng ta chiến thắng nhờ Đức Giêsu Kitô, Chúa chúng ta." },
  { id: 14, quote: "2 Cr 5,17", text: "Cho nên, phàm ai ở trong Đức Kitô đều là thụ tạo mới. Cái cũ đã qua, và cái mới đã có đây rồi." },
  { id: 15, quote: "Ep 2,4-5", text: "Thiên Chúa giàu lòng thương xót, đã cho chúng ta cùng được tái sinh với Đức Kitô." },
  { id: 16, quote: "1 Cr 15,55", text: "Hỡi tử thần, đâu là chiến thắng của ngươi? Hỡi tử thần, đâu là nọc độc của ngươi?" },
  { id: 17, quote: "Ga 3,16", text: "Thiên Chúa yêu thế gian đến nỗi đã ban Con Một, để ai tin vào Con của Người thì khỏi phải chết, nhưng được sống muôn đời." },
  { id: 18, quote: "Kh 1,18", text: "Ta là Đấng Hằng Sống, Ta đã chết, và nay Ta sống đến muôn thuở muôn đời." },
  { id: 19, quote: "Pl 3,10", text: "Vấn đề là được biết Đức Kitô, nhất là biết quyền năng phục sinh của Người." },
  { id: 20, quote: "Ga 16,22", text: "Bây giờ anh em lo sầu, nhưng Thầy sẽ gặp lại anh em, lòng anh em sẽ vui mừng, và niềm vui của anh em không ai lấy mất được." },
  { id: 21, quote: "1 Ga 5,4", text: "Mọi loài sinh ra bởi Thiên Chúa đều chiến thắng thế gian; và đây là chiến thắng đã thắng thế gian: Đức tin của chúng ta." },
  { id: 22, quote: "1 Cr 6,14", text: "Thiên Chúa đã làm cho Chúa Giêsu trỗi dậy, Người cũng sẽ dùng quyền năng của mình mà làm cho chúng ta trỗi dậy." },
  { id: 23, quote: "Cl 2,12", text: "Trong phép rửa, anh em đã cùng được mai táng với Đức Kitô, và cũng được trỗi dậy với Người." },
  { id: 24, quote: "Gl 2,20", text: "Tôi sống, nhưng không còn phải là tôi, mà là Đức Kitô sống trong tôi." },
  { id: 25, quote: "Ga 20,21", text: "Đức Giêsu lại nói với các ông: Bình an cho anh em! Như Chúa Cha đã sai Thầy, thì Thầy cũng sai anh em." },
  { id: 26, quote: "Pl 4,13", text: "Tôi im hơi lặng tiếng trước mọi hoàn cảnh, vì tôi có thể làm được mọi sự nhờ Đấng ban sức mạnh cho tôi." },
  { id: 27, quote: "Ga 6,40", text: "Ý của Cha Ta là tất cả những ai thấy Người Con và tin vào Người Con, thì được sống muôn đời, và Ta sẽ cho họ sống lại trong ngày sau hết." },
  { id: 28, quote: "Rm 5,8", text: "Đức Kitô đã chết vì chúng ta ngay khi chúng ta còn là những người tội lỗi; đó là bằng chứng Thiên Chúa yêu thương chúng ta." },
  { id: 29, quote: "1 Pr 2,24", text: "Tội lỗi của chúng ta, chính Người đã mang vào thân thể mà đưa lên cây gỗ, để chúng ta chết đối với tội lỗi và sống cho sự công chính." },
  { id: 30, quote: "2 Cr 4,14", text: "Chúng tôi biết rằng Đấng đã làm cho Chúa Giêsu trỗi dậy cũng sẽ làm cho chúng tôi trỗi dậy với Chúa Giêsu." },
  { id: 31, quote: "1 Cr 15,22", text: "Như mọi người vì liên đới với A-đam mà phải chết, thì mọi người nhờ liên đới với Đức Kitô cũng được Thiên Chúa cho sống." },
  { id: 32, quote: "Ep 1,7", text: "Trong Đức Kitô, nhờ máu Người đổ ra, chúng ta được cứu chuộc, được thứ tha tội lỗi theo lượng ân sủng dồi dào của Người." },
  { id: 33, quote: "Cv 4,33", text: "Các Tông Đồ làm chứng về sự phục sinh của Chúa Giêsu với quyền năng mạnh mẽ, và tất cả đều được tràn đầy ân sủng." },
  { id: 34, quote: "Ga 5,24", text: "Ai nghe lời Ta và tin Đấng đã sai Ta, thì có sự sống đời đời, và không bị xét xử, nhưng đã chuyển từ cõi chết sang cõi sống." },
  { id: 35, quote: "Tt 2,11", text: "Ân sủng của Thiên Chúa đã được biểu lộ, đem ơn cứu độ đến cho mọi người." }
];

export const PENTECOST_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Lc 11,13", text: "Cha trên trời sẽ ban Đấng Thánh Thần cho những kẻ xin Người." },
  { id: 2, quote: "Is 11,2", text: "Thần khí của Đức Chúa sẽ ngự trên vị ấy: thần khí khôn ngoan và thông minh." },
  { id: 3, quote: "Is 11,2", text: "Thần khí lo liệu và sức mạnh, thần khí hiểu biết và kính sợ Đức Chúa." },
  { id: 4, quote: "Gl 5,22", text: "Hoa quả của Thần Khí là: bác ái, hoan lạc, bình an, nhẫn nại, nhân hậu, từ tâm." },
  { id: 5, quote: "Gl 5,23", text: "Trung tín, hiền hòa, tiết độ. Không luật nào chống lại những điều như thế." },
  { id: 6, quote: "Ga 14,26", text: "Đấng Bảo Trợ là Thánh Thần sẽ dạy anh em mọi điều và làm cho anh em nhớ lại mọi điều Thầy đã nói." },
  { id: 7, quote: "Cv 1,8", text: "Anh em sẽ nhận được sức mạnh của Thánh Thần khi Người ngự xuống trên anh em." },
  { id: 8, quote: "Rm 8,26", text: "Thần Khí giúp đỡ chúng ta là những kẻ yếu hèn, vì chúng ta không biết cầu nguyện thế nào cho phải." },
  { id: 9, quote: "Rm 5,5", text: "Thiên Chúa đã đổ tình yêu của Người vào lòng chúng ta nhờ Thánh Thần mà Người ban cho chúng ta." },
  { id: 10, quote: "Ez 36,27", text: "Ta sẽ đặt thần khí Ta vào lòng các ngươi, làm cho các ngươi đi theo thánh chỉ của Ta." },
  { id: 11, quote: "1 Cr 3,16", text: "Anh em không biết rằng anh em là Đền Thờ của Thiên Chúa, và Thần Khí Thiên Chúa ngự trong anh em sao?" },
  { id: 12, quote: "Rm 8,14", text: "Phàm ai được Thần Khí Thiên Chúa dẫn dắt, đều là con cái Thiên Chúa." },
  { id: 13, quote: "Ga 16,13", text: "Khi nào Thần Khí sự thật đến, Người sẽ dẫn anh em tới sự thật toàn vẹn." },
  { id: 14, quote: "Cv 2,4", text: "Ai nấy đều được tràn đầy ơn Thánh Thần, họ bắt đầu nói các thứ tiếng khác nhau." },
  { id: 15, quote: "Rm 8,16", text: "Chính Thần Khí chứng thực cho thần trí chúng ta rằng chúng ta là con cái Thiên Chúa." },
  { id: 16, quote: "2 Tm 1,7", text: "Thiên Chúa đã chẳng ban cho chúng ta một thần khí nhút nhát, nhưng là một Thần Khí mạnh mẽ, đầy tình thương và tự chủ." }
];

export const LENT_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Cl 2,12", text: "Hãy thật lòng trở về với Ta trong chay tịnh, nước mắt và than van." },
  { id: 2, quote: "Tv 51,12", text: "Lạy Chúa, xin tạo cho con một tấm lòng trong sạch, và ban lại cho con một thần khí hiên ngang." },
  { id: 3, quote: "Tv 51,19", text: "Tế phẩm dâng Thiên Chúa là tâm hồn tan nát; một tấm lòng tan nát dày vò, Chúa sẽ chẳng khinh chê." },
  { id: 4, quote: "Mt 4,4", text: "Người ta sống không chỉ nhờ cơm bánh, nhưng còn nhờ mọi lời miệng Thiên Chúa phán ra." },
  { id: 5, quote: "Mt 6,6", text: "Khi cầu nguyện, hãy vào phòng, đóng cửa lại, và cầu nguyện cùng Cha của con, Đấng hiện diện nơi kín đáo." },
  { id: 6, quote: "Mt 6,18", text: "Để người ta không thấy con ăn chay, nhưng chỉ Cha con Đấng ngự nơi kín đáo thấy." },
  { id: 7, quote: "Is 58,6", text: "Cách ăn chay Ta ưa thích: là tháo xiềng xích bất công, tháo gông buộc trên cổ, trả tự do cho người bị áp bức." },
  { id: 8, quote: "Is 58,7", text: "Chia cơm sẻ áo cho người đói nghèo, rước vào nhà những kẻ không nơi nương tựa." },
  { id: 9, quote: "Lc 9,23", text: "Ai muốn theo tôi, phải từ bỏ chính mình, vác thập giá mình hằng ngày mà theo." },
  { id: 10, quote: "Lc 15,18", text: "Tôi muốn ra đi, trở về cùng cha tôi và thưa người: Thưa cha, con thật có lỗi với Trời và với cha." },
  { id: 11, quote: "Ga 3,16", text: "Thiên Chúa yêu thế gian đến nỗi đã ban Con Một, để ai tin vào Con của Người thì khỏi phải chết, nhưng được sống muôn đời." },
  { id: 12, quote: "1 Pr 4,8", text: "Trước hết, anh em hãy hết lòng yêu thương nhau, vì tình yêu che phủ muôn vàn tội lỗi." },
  { id: 13, quote: "Rm 5,8", text: "Thiên Chúa chứng tỏ tình yêu của Người đối với chúng ta: khi chúng ta còn là những người tội lỗi, Đức Kitô đã chết vì chúng ta." },
  { id: 14, quote: "Pl 3,10", text: "Tôi chỉ mong được biết Đức Kitô, nhất là biết quyền năng phục sinh của Người và được thông phần đau khổ với Người." },
  { id: 15, quote: "Mc 1,15", text: "Thời kỳ đã mãn, và Triều Đại Thiên Chúa đã đến gần. Anh em hãy sám hối và tin vào Tin Mừng." },
  { id: 16, quote: "2 Cr 6,2", text: "Đây là thiên thời, đây là ngày cứu độ; xin cho anh/chị siêng năng hòa giải cùng Chúa." }
];

export const ADVENT_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Mt 24,42", text: "Anh em hãy canh thức, vì anh em không biết ngày nào Chúa của anh em sẽ đến." },
  { id: 2, quote: "Mc 13,33", text: "Anh em phải coi chừng, phải tỉnh thức, vì anh em không biết khi nào thời kỳ đó đến." },
  { id: 3, quote: "Lc 3,4", text: "Có tiếng người hô trong hoang địa: Hãy dọn sẵn con đường của Đức Chúa, sửa lối cho thẳng để Người đi." },
  { id: 4, quote: "Lc 3,6", text: "Và mọi người phàm sẽ nhìn thấy ơn cứu độ của Thiên Chúa." },
  { id: 5, quote: "Is 40,31", text: "Những người cậy trông vào Đức Chúa sẽ được thêm sức mạnh, cánh họ mọc cánh đại bàng, họ chạy mà không mệt." },
  { id: 6, quote: "Lc 21,36", text: "Anh em hãy tỉnh thức và cầu nguyện luôn, để có đủ sức thoát khỏi mọi điều sắp xảy ra." },
  { id: 7, quote: "Rm 13,11", text: "Đã đến giờ anh em phải thức dậy, vì hiện nay ơn cứu độ đã gần chúng ta hơn." },
  { id: 8, quote: "Rm 13,12", text: "Đêm sắp tàn, ngày gần đến. Chúng ta hãy loại bỏ những việc làm đen tối, và mặc lấy vũ khí của sự sáng." },
  { id: 9, quote: "Pl 4,5", text: "Anh em hãy ăn ở hiền hòa với mọi người, vì Chúa đã gần đến." },
  { id: 10, quote: "Gc 5,8", text: "Anh em cũng vậy, hãy kiên nhẫn và bền chí, vì ngày Chúa quang lâm đã gần rồi." },
  { id: 11, quote: "Kh 22,20", text: "Đấng làm chứng về những điều ấy phán: Phải, Ta đến đây mau chóng! Amen, lạy Chúa Giêsu, xin ngự đến!" },
  { id: 12, quote: "Is 7,14", text: "Này đây người thiếu nữ mang thai, sinh hạ con trai, và đặt tên là Em-ma-nu-en." },
  { id: 13, quote: "Is 30,18", text: "Đức Chúa hằng chờ đợi để thi ân cho các ngươi; phúc thay mọi kẻ đợi trông Người." },
  { id: 14, quote: "Xp 3,17", text: "Đức Chúa là Thiên Chúa của ngươi ở cùng ngươi; Người hân hoan vui mừng vì có ngươi." },
  { id: 15, quote: "Tv 130,5", text: "Hồn tôi trông chờ Chúa, tôi trông cậy ở lời Người." },
  { id: 16, quote: "Tv 25,5", text: "Xin dẫn con đi theo đường chân lý của Ngài, vì Ngài là Thiên Chúa cứu độ con; suốt ngày con hằng trông cậy Ngài." }
];

export const MARIAN_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Lc 1,38", text: "Bà Maria nói: Vâng, tôi đây là nữ tỳ của Chúa, xin Chúa thực hiện cho tôi như lời sứ thần truyền." },
  { id: 2, quote: "Lc 1,42", text: "Bà Ê-li-sa-bét kêu lên: Em được chúc phúc hơn mọi người phụ nữ, và người con em đang cưu mang cũng được chúc phúc." },
  { id: 3, quote: "Lc 1,45", text: "Em thật có phúc, vì đã tin rằng Chúa sẽ thực hiện những gì Người đã phán với em." },
  { id: 4, quote: "Lc 1,46", text: "Linh hồn tôi ngợi khen Đức Chúa, thần trí tôi hớn hở vui mừng vì Thiên Chúa, Đấng cứu độ tôi." },
  { id: 5, quote: "Lc 1,48", text: "Phận nữ tỳ hèn mọn, Người đoái thương nhìn tới; từ nay, hết mọi đời sẽ khen tôi có phúc." },
  { id: 6, quote: "Lc 1,49", text: "Đấng Toàn Năng đã làm cho tôi biết bao điều cao cả, Danh Người thật chí thánh chí tôn." },
  { id: 7, quote: "Lc 2,19", text: "Còn bà Maria thì hằng ghi nhớ mọi kỷ niệm ấy, và suy đi nghĩ lại trong lòng." },
  { id: 8, quote: "Lc 2,51", text: "Riêng mẹ Người thì hằng ghi nhớ tất cả những điều ấy trong lòng." },
  { id: 9, quote: "Ga 2,5", text: "Thân mẫu Người nói với gia nhân: Người bảo gì, các anh cứ việc làm theo." },
  { id: 10, quote: "Ga 19,26", text: "Đức Giêsu nói với thân mẫu: Thưa Bà, đây là con của Bà." },
  { id: 11, quote: "Ga 19,27", text: "Rồi Người nói với môn đệ: Đây là mẹ của anh." },
  { id: 12, quote: "Lc 11,28", text: "Đức Giêsu đáp: Đúng hơn, phúc thay kẻ lắng nghe và tuân giữ lời Thiên Chúa." },
  { id: 13, quote: "Cv 1,14", text: "Tất cả các ông đều đồng tâm nhất trí, siêng năng cầu nguyện cùng với mấy người phụ nữ, với bà Maria thân mẫu Đức Giêsu." },
  { id: 14, quote: "Lc 1,28", text: "Sứ thần vào nhà và nói: Mừng vui lên, hỡi Đấng đầy ân sủng, Đức Chúa ở cùng bà." },
  { id: 15, quote: "Lc 1,30", text: "Sứ thần nói: Thưa bà Maria, xin đừng sợ, vì bà đẹp lòng Thiên Chúa." },
  { id: 16, quote: "Kh 12,1", text: "Một điềm lạ vĩ đại xuất hiện trên trời: một người Phụ Nữ mình khoác mặt trời, chân đạp vầng trăng." }
];

export const ST_JOSEPH_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Mt 1,19", text: "Ông Giu-se, chồng bà, là người công chính và không muốn tố giác bà, nên mới định tâm bỏ bà cách kín đáo." },
  { id: 2, quote: "Mt 1,24", text: "Khi tỉnh giấc, ông Giu-se làm như sứ thần Chúa truyền và đón vợ về nhà." },
  { id: 3, quote: "Mt 2,14", text: "Ông Giu-se liền trỗi dậy, ban đêm, đưa Hài Nhi và mẹ Người trốn sang Ai-cập." },
  { id: 4, quote: "Mt 2,21", text: "Ông liền trỗi dậy, đưa Hài Nhi và mẹ Người về đất Ít-ra-en." },
  { id: 5, quote: "Mt 13,55", text: "Ông ta không phải là con bác thợ mộc sao? Mẹ của ông ta không phải là bà Maria sao?" },
  { id: 6, quote: "Lc 2,48", text: "Cha con và mẹ đây đã phải cực lòng tìm con!" },
  { id: 7, quote: "Tv 128,1", text: "Hạnh phúc thay bạn nào kính sợ Chúa, ăn ở theo đường lối của Người." },
  { id: 8, quote: "Tv 128,2", text: "Công lao tay bạn làm, bạn được an hưởng, bạn được hạnh phúc và gặp mọi điều may." },
  { id: 9, quote: "Cn 28,20", text: "Người trung tín sẽ được tràn ngập phúc lành." },
  { id: 10, quote: "Lc 12,42", text: "Ai là người quản gia trung tín, khôn ngoan được chủ đặt lên coi sóc gia nhân?" },
  { id: 11, quote: "Mt 25,21", text: "Khá lắm, hỡi đầy tớ tài giỏi và trung thành! Hãy vào hưởng niềm vui của chủ ngươi!" },
  { id: 12, quote: "Pl 2,8", text: "Người đã hạ mình, vâng lời cho đến nỗi bằng lòng chịu chết, chết trên cây thập tự." },
  { id: 13, quote: "Cl 3,23", text: "Bất cứ làm việc gì, hãy làm tận tâm như làm cho Chúa, chứ không phải cho người phàm." },
  { id: 14, quote: "Tv 37,3", text: "Hãy tin tưởng vào Đức Chúa và làm điều lành, thì sẽ được ký thác trên đất an toàn." },
  { id: 15, quote: "Tv 37,23", text: "Đức Chúa giúp người hiền bước đi vững chãi, Người ưa thích đường lối họ qua." },
  { id: 16, quote: "Mt 2,22", text: "Được báo mộng, ông Giu-se lui về miền Ga-li-lê, lập nghiệp tại một thành kia gọi là Na-da-rét." }
];

export const EUCHARIST_BLESSINGS: BlessingItem[] = [
  { id: 1, quote: "Ga 6,35", text: "Chính Thầy là bánh trường sinh. Ai đến với Thầy, không hề phải đói; ai tin vào Thầy, không bao giờ khát." },
  { id: 2, quote: "Ga 6,51", text: "Thầy là bánh hằng sống từ trời xuống. Ai ăn bánh này, sẽ được sống muôn đời." },
  { id: 3, quote: "Ga 6,54", text: "Ai ăn thịt và uống máu Thầy, thì được sống muôn đời, và Thầy sẽ cho người ấy sống lại vào ngày sau hết." },
  { id: 4, quote: "Ga 6,56", text: "Ai ăn thịt và uống máu Thầy, thì ở lại trong Thầy, và Thầy ở lại trong người ấy." },
  { id: 5, quote: "Ga 6,57", text: "Như Cha là Đấng Hằng Sống đã sai Thầy, kẻ ăn Thầy, cũng sẽ nhờ Thầy mà được sống." },
  { id: 6, quote: "Lc 22,19", text: "Người cầm lấy bánh, dâng lời tạ ơn, bẻ ra, trao cho các ông và nói: Đây là mình Thầy, hiến tế vì anh em." },
  { id: 7, quote: "Lc 22,20", text: "Chén này là giao ước mới, lập bằng máu Thầy, máu đổ ra vì anh em." },
  { id: 8, quote: "1 Cr 10,16", text: "Chén chúc tụng mà chúng ta ta ơn, đó chẳng phải là thông phần vào Máu Đức Kitô sao?" },
  { id: 9, quote: "1 Cr 11,26", text: "Thật vậy, mỗi lần ăn Bánh và uống Chén này, là anh em loan truyền Chúa chịu chết, cho tới khi Người đến." },
  { id: 10, quote: "Tv 34,9", text: "Hãy nghiệm xem Chúa tốt lành biết mấy: hạnh phúc thay kẻ ẩn náu bên Người!" },
  { id: 11, quote: "Ga 15,4", text: "Hãy ở lại trong Thầy như Thầy ở lại trong anh em; cành nho không thể tự mình sinh hoa trái nếu không gắn liền với cây nho." },
  { id: 12, quote: "Lc 24,30", text: "Khi đồng bàn với họ, Người cầm lấy bánh, dâng lời chúc tụng, bẻ ra và trao cho họ. Mắt họ liền mở ra và họ nhận ra Người." },
  { id: 13, quote: "Tv 116,12", text: "Biết lấy chi đền đáp Chúa bây giờ, vì mọi ơn lành Người đã ban cho?" },
  { id: 14, quote: "Tv 116,13", text: "Tôi xin nâng chén cứu độ và kêu cầu danh Chúa." },
  { id: 15, quote: "Ga 6,68", text: "Lạy Thầy, bỏ Thầy thì chúng con biết đến với ai? Thầy mới có những lời đem lại sự sống đời đời." },
  { id: 16, quote: "Ga 4,14", text: "Ai uống nước tôi cho, sẽ không bao giờ khát nữa. Nước tôi cho sẽ trở thành nơi người ấy một mạch nước vọt lên, đem lại sự sống đời đời." }
];

