/* ==========================================
   DANH SÁCH 100 LỜI CHÚA DỊU DÀNG CHO NGÀY TẾT
   Cơ sở dữ liệu Lời Chúa nâng đỡ tinh thần, chúc lành và bình an.
   ========================================== */

const BLESSINGS = [
  { id: 0, quote: "Giờ Cha Chờ", text: "Năm mới, Chúa mời gọi bạn siêng năng chạy đến với Người qua Bí Tích Hòa Giải và Thánh Lễ. Tải ứng dụng Giờ Cha Chờ tra cứu Giờ Lễ & Giờ Xưng Tội tại: https://play.google.com/store/apps/details?id=com.anonymous.churchfindernative&hl=vi" },
  { id: 1, quote: "Ds 6,24-26", text: "Xin Chúa chúc lành, gìn giữ và ban bình an cho anh/chị trong năm mới." },
  { id: 2, quote: "Tv 23,1", text: "Năm nay, anh/chị đừng lo thiếu thốn, vì Chúa là Đấng chăn dắt đời mình." },
  { id: 3, quote: "Tv 23,3", text: "Xin Chúa bổ sức tâm hồn và dẫn anh/chị đi trên đường ngay lành." },
  { id: 4, quote: "Tv 23,4", text: "Dù năm mới có điều chưa biết trước, anh/chị vẫn không đơn độc vì Chúa ở cùng." },
  { id: 5, quote: "Tv 27,1", text: "Chúa là ánh sáng của đời anh/chị; xin năm mới không còn sợ hãi." },
  { id: 6, quote: "Tv 29,11", text: "Xin Chúa ban sức mạnh và chúc lành bình an cho gia đình anh/chị." },
  { id: 7, quote: "Tv 31,25", text: "Hãy vững lòng, vì Chúa sẽ làm cho trái tim anh/chị mạnh mẽ hơn." },
  { id: 8, quote: "Tv 34,9", text: "Xin cho anh/chị cảm nhận được Chúa tốt lành trong từng ngày của năm mới." },
  { id: 9, quote: "Tv 37,4", text: "Hãy vui trong Chúa, Người sẽ chăm sóc những ước nguyện đẹp trong lòng anh/chị." },
  { id: 10, quote: "Tv 37,5", text: "Hãy phó thác đường đời cho Chúa, Người sẽ âm thầm mở lối cho anh/chị." },
  { id: 11, quote: "Tv 46,2", text: "Khi lòng chao đảo, xin anh/chị nhớ rằng Chúa là nơi nương náu vững vàng." },
  { id: 12, quote: "Tv 55,23", text: "Hãy trao những gánh nặng cũ cho Chúa, để bước vào năm mới nhẹ lòng hơn." },
  { id: 13, quote: "Tv 65,12", text: "Xin Chúa đội triều thiên ân phúc cho năm mới của anh/chị." },
  { id: 14, quote: "Tv 84,12", text: "Chúa chẳng từ chối điều tốt lành cho ai sống chân thành trước mặt Người." },
  { id: 15, quote: "Tv 85,9", text: "Xin bình an của Chúa trở về trong lòng và trong mái nhà anh/chị." },
  { id: 16, quote: "Tv 90,17", text: "Xin Chúa cho công việc tay anh/chị làm trong năm mới được vững bền." },
  { id: 17, quote: "Tv 91,11", text: "Xin Chúa sai thiên thần gìn giữ anh/chị trên mọi nẻo đường năm nay." },
  { id: 18, quote: "Tv 103,2", text: "Năm mới, xin anh/chị đừng quên bao ơn lành Chúa đã âm thầm ban." },
  { id: 19, quote: "Tv 118,24", text: "Đây là ngày Chúa làm ra; xin anh/chị vui lên và bắt đầu lại trong hy vọng." },
  { id: 20, quote: "Tv 121,5", text: "Chúa là Đấng canh giữ đời anh/chị, như bóng mát chở che bên cạnh." },
  { id: 21, quote: "Tv 121,7", text: "Xin Chúa gìn giữ anh/chị khỏi điều dữ và giữ tâm hồn luôn bình an." },
  { id: 22, quote: "Tv 121,8", text: "Xin Chúa gìn giữ anh/chị khi ra đi, lúc trở về, suốt cả năm mới." },
  { id: 23, quote: "Tv 126,5", text: "Ai đã gieo trong nước mắt, sẽ có ngày gặt trong tiếng cười." },
  { id: 24, quote: "Tv 127,1", text: "Xin Chúa xây dựng gia đình và công việc của anh/chị trong năm mới." },
  { id: 25, quote: "Tv 128,1-2", text: "Phúc cho ai kính sợ Chúa; họ sẽ hưởng thành quả do tay mình làm ra." },
  { id: 26, quote: "Tv 145,18", text: "Khi anh/chị thật lòng kêu cầu, Chúa luôn ở gần." },
  { id: 27, quote: "Cn 3,5-6", text: "Hãy tin tưởng Chúa, Người sẽ làm cho đường anh/chị đi được ngay thẳng." },
  { id: 28, quote: "Cn 16,3", text: "Hãy trao việc mình làm cho Chúa, dự định của anh/chị sẽ được Người nâng đỡ." },
  { id: 29, quote: "Gv 3,11", text: "Chúa làm mọi sự tốt đẹp đúng thời điểm của Người." },
  { id: 30, quote: "Is 26,3", text: "Ai cậy trông nơi Chúa sẽ được Người giữ gìn trong bình an." },
  { id: 31, quote: "Is 30,15", text: "Trong thinh lặng và tin tưởng, anh/chị sẽ tìm lại sức mạnh cho năm mới." },
  { id: 32, quote: "Is 35,4", text: "Hãy can đảm lên, đừng sợ; Thiên Chúa đang đến để cứu giúp anh/chị." },
  { id: 33, quote: "Is 40,29", text: "Chúa ban sức mạnh cho người mệt mỏi và nâng đỡ ai kiệt sức." },
  { id: 34, quote: "Is 40,31", text: "Ai trông cậy Chúa sẽ được thêm sức mới để bước tiếp." },
  { id: 35, quote: "Is 41,10", text: "Đừng sợ, vì Chúa ở cùng anh/chị và nâng đỡ anh/chị." },
  { id: 36, quote: "Is 41,13", text: "Chúa nắm lấy tay anh/chị và nói: đừng sợ, có Ta trợ giúp." },
  { id: 37, quote: "Is 43,1", text: "Chúa gọi anh/chị bằng tên; anh/chị thuộc về Người." },
  { id: 38, quote: "Is 43,2", text: "Qua nước sâu hay lửa thử thách, Chúa vẫn ở cùng anh/chị." },
  { id: 39, quote: "Is 43,19", text: "Năm mới, Chúa đang làm một điều mới và mở đường giữa nơi tưởng như bế tắc." },
  { id: 40, quote: "Is 44,3", text: "Xin Chúa đổ phúc lành xuống trên gia đình và con cháu anh/chị." },
  { id: 41, quote: "Is 46,4", text: "Chúa vẫn bồng ẵm, nâng niu và cứu giúp anh/chị qua từng mùa đời." },
  { id: 42, quote: "Is 49,15", text: "Dù ai quên anh/chị, Chúa vẫn không bao giờ quên." },
  { id: 43, quote: "Is 54,10", text: "Núi có dời, đồi có chuyển, tình thương Chúa dành cho anh/chị vẫn không đổi." },
  { id: 44, quote: "Is 58,11", text: "Chúa sẽ luôn dẫn dắt và làm tâm hồn anh/chị như khu vườn được tưới mát." },
  { id: 45, quote: "Is 60,1", text: "Hãy đứng lên và tỏa sáng, vì ánh sáng của Chúa đã đến với anh/chị." },
  { id: 46, quote: "Gr 17,7", text: "Phúc cho người đặt niềm tin nơi Chúa, vì lòng họ có chỗ tựa vững bền." },
  { id: 47, quote: "Gr 17,8", text: "Người cậy trông Chúa như cây bên dòng nước, vẫn xanh tươi trong ngày nắng hạn." },
  { id: 48, quote: "Gr 29,11", text: "Chúa có kế hoạch bình an và tương lai đầy hy vọng cho anh/chị." },
  { id: 49, quote: "Gr 31,3", text: "Chúa yêu anh/chị bằng tình yêu muôn thuở." },
  { id: 50, quote: "Ac 3,22-23", text: "Lòng thương xót Chúa luôn mới mỗi buổi sáng; năm mới cũng là một khởi đầu mới." },
  { id: 51, quote: "Ed 36,26", text: "Xin Chúa ban cho anh/chị một trái tim mới, mềm mại và bình an hơn." },
  { id: 52, quote: "Ge 2,21", text: "Đừng sợ, hãy vui mừng, vì Chúa đang thực hiện những điều lớn lao." },
  { id: 53, quote: "Mk 7,7", text: "Dù có vấp ngã, anh/chị vẫn có thể đứng lên nhờ Chúa là ánh sáng." },
  { id: 54, quote: "Na 1,7", text: "Chúa tốt lành, là thành lũy chở che trong ngày gian khó." },
  { id: 55, quote: "Xp 3,17", text: "Chúa ở giữa anh/chị, vui mừng vì anh/chị và lấy tình thương mà đổi mới." },
  { id: 56, quote: "Mt 5,4", text: "Phúc cho ai sầu khổ, vì họ sẽ được Thiên Chúa ủi an." },
  { id: 57, quote: "Mt 5,5", text: "Phúc cho ai hiền lành, vì Chúa sẽ ban cho họ phần gia nghiệp tốt đẹp." },
  { id: 58, quote: "Mt 5,7", text: "Phúc cho ai biết xót thương, vì họ sẽ được Chúa xót thương." },
  { id: 59, quote: "Mt 5,9", text: "Phúc cho ai xây dựng hòa bình, vì họ được gọi là con Thiên Chúa." },
  { id: 60, quote: "Mt 6,26", text: "Chúa chăm sóc chim trời, huống chi là anh/chị quý giá trước mặt Người." },
  { id: 61, quote: "Mt 6,31-33", text: "Đừng quá lo lắng; hãy tìm Chúa trước, Người sẽ lo liệu điều cần thiết." },
  { id: 62, quote: "Mt 7,7", text: "Hãy xin, hãy tìm, hãy gõ; Chúa sẽ mở cửa cho anh/chị." },
  { id: 63, quote: "Mt 11,28", text: "Hãy đến với Chúa khi mỏi mệt, Người sẽ cho anh/chị được nghỉ ngơi." },
  { id: 64, quote: "Mt 11,29", text: "Hãy học với Chúa sự hiền lành và khiêm nhường, tâm hồn anh/chị sẽ được an nghỉ." },
  { id: 65, quote: "Mt 19,26", text: "Với Thiên Chúa, điều tưởng như không thể vẫn có thể thành hiện thực." },
  { id: 66, quote: "Mt 28,20", text: "Chúa ở cùng anh/chị mọi ngày trong năm mới này." },
  { id: 67, quote: "Mc 5,36", text: "Đừng sợ, chỉ cần tin thôi." },
  { id: 68, quote: "Mc 9,23", text: "Ai tin thì mọi sự đều có thể trong quyền năng Chúa." },
  { id: 69, quote: "Mc 10,27", text: "Điều con người không làm được, Thiên Chúa vẫn làm được." },
  { id: 70, quote: "Lc 1,37", text: "Không có gì là không thể đối với Thiên Chúa." },
  { id: 71, quote: "Lc 1,45", text: "Phúc cho ai tin rằng Chúa sẽ thực hiện lời Người đã hứa." },
  { id: 72, quote: "Lc 2,14", text: "Xin bình an của Chúa ở với anh/chị và gia đình trong năm mới." },
  { id: 73, quote: "Lc 6,36", text: "Xin cho trái tim anh/chị trong năm mới biết nhân từ như Cha trên trời." },
  { id: 74, quote: "Lc 10,20", text: "Hãy vui mừng vì tên anh/chị được ghi trong tình thương của Chúa." },
  { id: 75, quote: "Lc 12,32", text: "Đừng sợ, vì Cha trên trời vui lòng ban điều tốt lành cho anh/chị." },
  { id: 76, quote: "Ga 8,12", text: "Ai theo Chúa sẽ không đi trong tối tăm nhưng có ánh sáng sự sống." },
  { id: 77, quote: "Ga 10,10", text: "Chúa đến để anh/chị được sống và sống dồi dào hơn." },
  { id: 78, quote: "Ga 14,1", text: "Đừng để lòng xao xuyến; hãy tin vào Thiên Chúa." },
  { id: 79, quote: "Ga 14,27", text: "Chúa ban cho anh/chị bình an không giống bình an chóng qua của thế gian." },
  { id: 80, quote: "Ga 15,5", text: "Ở lại trong Chúa, đời anh/chị sẽ sinh nhiều hoa trái tốt lành." },
  { id: 81, quote: "Ga 15,9", text: "Hãy ở lại trong tình yêu của Chúa suốt năm mới này." },
  { id: 82, quote: "Ga 15,11", text: "Xin niềm vui của Chúa ở trong anh/chị và làm cho niềm vui ấy nên trọn vẹn." },
  { id: 83, quote: "Ga 16,33", text: "Hãy can đảm, vì Chúa đã thắng thế gian." },
  { id: 84, quote: "Cv 20,35", text: "Cho đi với tình yêu, anh/chị sẽ nhận lại niềm vui sâu hơn." },
  { id: 85, quote: "Rm 5,5", text: "Niềm hy vọng nơi Chúa không làm anh/chị thất vọng." },
  { id: 86, quote: "Rm 8,28", text: "Chúa làm cho mọi sự sinh ích cho những ai yêu mến Người." },
  { id: 87, quote: "Rm 8,31", text: "Nếu Thiên Chúa bênh đỡ anh/chị, còn gì phải sợ?" },
  { id: 88, quote: "Rm 8,39", text: "Không gì có thể tách anh/chị khỏi tình yêu của Thiên Chúa." },
  { id: 89, quote: "Rm 12,12", text: "Hãy vui mừng trong hy vọng, kiên nhẫn khi gian truân và bền lòng cầu nguyện." },
  { id: 90, quote: "Rm 15,13", text: "Xin Thiên Chúa là nguồn hy vọng đổ đầy niềm vui và bình an trong lòng anh/chị." },
  { id: 91, quote: "1 Cr 2,9", text: "Chúa chuẩn bị cho người yêu mến Người những điều vượt quá điều lòng người tưởng nghĩ." },
  { id: 92, quote: "1 Cr 13,4", text: "Xin tình yêu trong gia đình anh/chị năm mới này thêm nhẫn nại và hiền hậu." },
  { id: 93, quote: "2 Cr 5,17", text: "Trong Đức Kitô, anh/chị được bắt đầu lại như một thụ tạo mới." },
  { id: 94, quote: "2 Cr 9,8", text: "Chúa có thể ban dư đầy ân sủng để anh/chị luôn đủ sức làm điều lành." },
  { id: 95, quote: "2 Cr 12,9", text: "Ơn Chúa đủ cho anh/chị, nhất là trong những lúc yếu lòng." },
  { id: 96, quote: "Gl 5,22", text: "Xin Thánh Thần ban cho anh/chị yêu thương, vui mừng, bình an và hiền hòa." },
  { id: 97, quote: "Gl 6,9", text: "Đừng nản lòng khi làm điều thiện, vì đến mùa, anh/chị sẽ gặt hái." },
  { id: 98, quote: "Ep 3,20", text: "Chúa có thể làm cho anh/chị hơn cả điều anh/chị cầu xin hay nghĩ tới." },
  { id: 99, quote: "Pl 1,6", text: "Chúa đã khởi sự điều tốt lành nơi anh/chị và sẽ hoàn tất điều ấy." },
  { id: 100, quote: "Pl 4,7", text: "Xin bình an của Thiên Chúa gìn giữ lòng trí anh/chị trong năm mới." }
];
